config/routes.rb
Blogonhr::Application.routes.draw do

  resources :locations

  resources :blogs
  resources :dances   
  resources :homes
  resources :messages
  resources :movies
  resources :sessions
  
  match "/blogs", :to => "blogs#index"
  match "/dances", :to => "dances#index"
  match "/movies", :to => "movies#index"
  match "/contact" => "messages#new", :as => :contact
  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout
  
  

  
  root :to => "homes#index"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  require 'paperclip'
  has_attached_file :picture
  
  def self.all
    find(:all,  :order => "post_date DESC")
  end
  
  def self.find_recent
    find(:first, :order => "created_at DESC")
  end
  
  has_attached_file :picture,
    :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100>x100" }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout :resolve_layout
  before_filter :authorize, :except => [:index, :show]
  # GET /blogs
  # GET /blogs.xml
  def index
    @blogs = Blog.all
    @locations = Location.all
    @json = Location.all.to_gmaps4rails
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        flash[:notice] = 'Blog entry was successfully created.'
        format.html { redirect_to(@blog) }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(@blog, :notice => 'Blog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to(blogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<h2><%= blog.post_title%></h2>
<h3><%=blog.post_date.strftime("%x")%></h3>
<%if blog.picture.exists?%>
<br/>
<p><%= image_tag blog.picture.url(:medium)%></p>
<%end%>
<br/>
<div class="white">
<p ><%=RedCloth.new(blog.post_body).to_html.html_safe%></p>
<p><%if admin?%>
<%= link_to 'Edit', edit_blog_path(blog) %> |
<%= link_to "Destroy", blog, :confirm => 'Are you sure?', :method => :delete %> |
<%end%></p>
</div>
<br/><br/>

app/views/blogs/_post.html.erb
<div class="myforms">
<% form_for @blog, :html => { :multipart => true }  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :post_title %>
    <%= f.text_field :post_title %>
  </p>
<p>
    <%= f.label :post_date %>
    <%= f.date_select :post_date %>
  </p>
  <p>
    <%= f.label :post_body %>
    <%= f.text_area :post_body %>
  </p>
  <p>
    <%= f.label :picture, "Please upload a picture." %>
    <%= f.file_field :picture %>
  </p>
<br />
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class="show">
<h1>Edit post</h1>

<%= render :partial => 'post'%>


<br/>
<p><%= link_to 'Destroy', @post, :method=> :delete, :confirm => "Are you sure?" %> |
<%= link_to 'Back', blogs_path %></p>
</div>

app/views/blogs/index.html.erb
<div class="show">
<h1>The Trip</h1>
<br/>
<div class="smaller"><p>Waaaay back in 1980, when I heard that my first cousin had cycled across the U.S., I summarily decided, with a decisiveness that I now envy,
to do the same. The fact that said cousin is female was perhaps a factor ... hey, if a woman could do it ..</p>
<p>So I quit my job, and, with the $1500 profit from selling my treasured Volvo 122S, outfitted myself for the journey. My cousin had tipped me off to a 
set of guidebooks published by Missoula, MT-based Bikecentennial. The organization, inspired by the national Bicentennial, had plotted a cross-country route for
cyclists that kept as much as possible to back roads and provided elaborate detail about budget eating and camping along the way.</p> 
<p>Early in June I packed my new Fuji bicycle in a box and boarded a bus for Yorktown Virginia. Later that day I fumblingly reassembled the bike in
a Yorktown parking lot, attached my panniers, and rode a few miles to the ocean where I ceremoniously dunked my front tire. Then I started riding west.</p>
<p>Over 30 years later, I'm finally getting around to documenting the odyssey. To some extent the project found its rationale in this website, a vehicle for teaching myself the Ruby on Rails web development framework. 
But the method now seems like a good match for the episodic nature of the writing, especially when paired with the very cool Google maps gem for RoR, gmaps4rails.</p></div>

<br/>
<%= gmaps4rails(@json) %>

<%if admin?%>
<br/>
<p><%= link_to 'New Location', new_location_path %><p>
<%end%>
<br/>
<p><%= render :partial => @locations %></p>
<br/>
</div>

app/views/blogs/index_old.html.erb
<p class="login"><%=link_to 'Login', login_path%>|<%=link_to 'Logout', logout_path%></p>
<h1>Musings</h1>
<br/><br/>
<div class = "show">
<%if admin?%>
<p><%= link_to 'New post', new_blog_path %></p>
<%end%>
<br/>
<p><%= render :partial => @blogs %></p>
</div>

app/views/blogs/indexoldtwo.html.erb
<div id="ars_content">
<h1>The Trip</h1>
<br/>
<div><%= gmaps4rails(@json) %></div>
<p><%= link_to 'New Location', new_location_path %><p>
<p><%= render :partial => @locations %></p>
<br/>
<!-- end ars_content --></div>
<div id="everydaystuff">
<p class="login"><%=link_to 'Login', login_path%>|<%=link_to 'Logout', logout_path%></p>
<h1>Musings</h1>
<%if admin?%>
<p><%= link_to 'New entry', new_blog_path %></p>
<%end%>
<br/>
<%= render :partial => @blogs %>
<!-- end everydaystuff --></div>

app/views/blogs/new.html.erb
<div class="show">
<h1>New blog post</h1>
<%= render :partial => 'post'%>
<br/>
<p><%= link_to 'Back', blogs_path %></p>
<br/>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <b>Post title:</b>
  <%= @blog.post_title %>
</p>

<p>
  <b>Post date:</b>
  <%= @blog.post_date %>
</p>

<p>
  <b>Post body:</b>
  <%= @blog.post_body %>
</p>
<br/>
<p>
<%if admin?%>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to "Destroy", @blogs, :confirm => 'Are you sure?', :method => :delete %> |
<%end%>
<%= link_to 'All Posts', blog_path %></p>
</div>