config/routes.rb
Blogonhr::Application.routes.draw do

  resources :locations

  resources :blogs
  resources :dances   
  resources :homes
  resources :messages
  resources :movies
  resources :sessions
  
  match "/blogs", :to => "blogs#index"
  match "/dances", :to => "dances#index"
  match "/movies", :to => "movies#index"
  match "/contact" => "messages#new", :as => :contact
  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout
  
  

  
  root :to => "homes#index"
end

app/models/dance.rb
class Dance < ActiveRecord::Base
   require 'paperclip'
  has_attached_file :photo
  
  def self.all
    find(:all,  :order => "dance_date_one DESC")
  end
  
  def self.find_recent
    find(:first, :order => "created_at DESC")
  end
  
  has_attached_file :photo,
    :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100>x100" }
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
  before_filter :authorize, :except => [:index, :show]
  # GET /dances
  # GET /dances.xml
  def index
    @dances = Dance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dances }
    end
  end

  # GET /dances/1
  # GET /dances/1.xml
  def show
    @dance = Dance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dance }
    end
  end

  # GET /dances/new
  # GET /dances/new.xml
  def new
    @dance = Dance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dance }
    end
  end

  # GET /dances/1/edit
  def edit
    @dance = Dance.find(params[:id])
  end

  # POST /dances
  # POST /dances.xml
  def create
    @dance = Dance.new(params[:dance])

    respond_to do |format|
      if @dance.save
        flash[:notice] = 'Dance was successfully created.'
        format.html { redirect_to(@dance) }
        format.xml  { render :xml => @dance, :status => :created, :location => @dance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dances/1
  # PUT /dances/1.xml
  def update
    @dance = Dance.find(params[:id])

    respond_to do |format|
      if @dance.update_attributes(params[:dance])
        flash[:notice] = 'Dance was successfully updated.'
        format.html { redirect_to(@dance) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dances/1
  # DELETE /dances/1.xml
  def destroy
    @dance = Dance.find(params[:id])
    @dance.destroy

    respond_to do |format|
      format.html { redirect_to(dances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/views/dances/_dance.html.erb
<h2><%= dance.dance_name%> - <%= h(dance.dance_date_one.strftime("%x"))%> </h2>
<p><b>Location:</b> <%= dance.dance_location%></p>
<p><b>Time:</b> <%= h(dance.dance_time.strftime("%I:%M"))%></p>
<p><b>Lessons:</b> Lesson One - <%= h(dance.lesson_one_description)%> - <%= h(dance.lesson_one_time.strftime("%I:%M%p"))%></p>
<br/>
<p><%= image_tag dance.photo.url(:medium)%></p>
<br/>
<p><%=truncate(dance.dance_description, :length => 100, :separator => ' ')%></p>
<p><span><%= link_to_unless_current h("More"), dance%></span></p>
<br/><br/>

app/views/dances/_onedance.html.erb
<div class="myforms">
<% form_for @dance, :html => { :multipart => true }  do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :dance_name %>
    <%= f.text_field :dance_name %>
  </p>
  <p>
    <%= f.label :dance_location %>
    <%= f.text_field :dance_location %>
  </p>
<p>
    <%= f.label :dance_date_one %>
    <%= f.date_select :dance_date_one %>
  </p>
<p>
    <%= f.label :dance_date_two %>
    <%= f.date_select :dance_date_two %>
  </p>
<p>
    <%= f.label :dance_time %>
    <%= f.time_select :dance_time %>
  </p>
<p>
    <%= f.label :lesson_one_description %>
    <%= f.text_field :lesson_one_description %>
  </p>
<p>
    <%= f.label :lesson_one_time %>
    <%= f.time_select :lesson_one_time %>
  </p>
<p>
    <%= f.label :lesson_two_description %>
    <%= f.text_field :lesson_two_description %>
  </p>
  <p>
    <%= f.label :Lesson_two_time %>
    <%= f.time_select :lesson_two_time %>
  </p>
  <p>
    <%= f.label :dance_description %>
    <%= f.text_area :dance_description %>
  </p>
  <p>
    <%= f.label :photo, "Please upload a dance photo." %>
    <%= f.file_field :photo %>
  </p>
<br />
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>
</div>

app/views/dances/edit.html.erb
<div class="show">
<h1>Editing dance</h1>

<%= render :partial => 'onedance'%>

<p>
<%= link_to 'Destroy', @dance, :method=> :delete, :confirm => "Are you sure?" %> |
<%= link_to 'Back', dances_path %></p>
</div>

app/views/dances/index.html.erb
<div class="show">
<p class="login"><%=link_to 'Login', login_path%>|<%=link_to 'Logout', logout_path%></p>
<h1>Dances</h1>
<br/><br/>
<%if admin?%>
<p><%= link_to 'New dance', new_dance_path %></p>
<%end%>
<br/>
<p><%= render :partial => @dances %></p>
</div>

app/views/dances/new.html.erb
<div class="show">
<h1>Create new dance</h1>
<%= render :partial => 'onedance'%>
<%= link_to 'Back', dances_path %>
</div>

app/views/dances/show.html.erb
<div class="show">
<% div_for @dance do%>
<p><%= image_tag @dance.photo.url(:large)%></p>
<br/>
<h2><%= @dance.dance_name%></h2>
<p><b><%= @dance.dance_location%></b></p>
<p><b><%= h(@dance.dance_date_one.strftime("%A, %x"))%> - <%= h(@dance.dance_time.strftime("%I:%M %p"))%></b></p>
<p><b>Lesson One - <%= h(@dance.lesson_one_description)%></b> - <b><%= h(@dance.lesson_one_time.strftime("%I:%M %p"))%></b></p>
<br/>
<p ><%= @dance.dance_description%></p>
<%end%>
<br/>
<p>
<%if admin?%>
<%= link_to 'Edit', edit_dance_path(@dance) %> |
<%= link_to "Destroy", @dances, :confirm => 'Are you sure?', :method => :delete %> |
<%end%>
<%= link_to 'All Dances', dances_path %>
</p>
</div>