config/routes.rb
Blogonhr::Application.routes.draw do

  resources :locations

  resources :blogs
  resources :dances   
  resources :homes
  resources :messages
  resources :movies
  resources :sessions
  
  match "/blogs", :to => "blogs#index"
  match "/dances", :to => "dances#index"
  match "/movies", :to => "movies#index"
  match "/contact" => "messages#new", :as => :contact
  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout
  
  

  
  root :to => "homes#index"
end

app/models/location.rb
class Location < ActiveRecord::Base
    acts_as_gmappable
    
     def self.all
      find(:all,  :order => "tripday_date ASC")
    end
  
    
    def gmaps4rails_address
      "#{self.location_name}, #{self.location_address}"
    end
    
    def gmaps4rails_infowindow
      "<h4>#{location_name}</h4>" << "<h4>#{location_address}</h4>"
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout :resolve_layout
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])
    @onelocation = Location.find(params[:id]).to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to(@location, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(@location, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name %>
  </div>
  <div class="field">
    <%= f.label :location_address %><br />
    <%= f.text_field :location_address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :tripday_date %><br />
       <%= f.date_select("tripday_date", :start_year => 1980) %>
  </div>
  <div class="field">
    <%= f.label :tripday_log %><br />
    <%= f.text_area :tripday_log %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<h3><%= location.tripday_date.strftime("%x")%> - <%=h(location.location_address)%></h3>
<p><%=truncate((RedCloth.new(location.tripday_log)).to_html, :length => 200, :separator => ' ').html_safe%></p>
<span class="more"><%= link_to_unless_current h("More"), location%></span>
<br/>

app/views/locations/_onelocation.html.erb
<div class="myforms">
<% form_for (@location) do |f| %>
  <%= f.error_messages %>
  <p>
   <%= f.label :location_name %>
    <%= f.text_field :location_name %>
  </p>
  <p>
    <%= f.label :location_address %>
    <%= f.text_field :location_address %>
  </p>
<p>
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </p>
<p>
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </p>
<p>
    <%= f.label :tripday_date %>
    <%= f.date_select("tripday_date", :start_year => 1980) %>

  </p>
<p>
    <%= f.label :tripday_log %>
    <%= f.text_area :tripday_log %>
  </p>
<br />
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

app/views/locations/edit.html.erb
<div class="show">
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>
</div>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Location name</th>
    <th>Location address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Tripday date</th>
    <th>Tripday log</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.location_name %></td>
    <td><%= location.location_address %></td>
    <td><%= location.longitude %></td>
    <td><%= location.latitude %></td>
    <td><%= location.tripday_date %></td>
    <td><%= location.tripday_log %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<div class="show">
<h1>New location</h1>
<%= render :partial => 'onelocation'%>
<%= link_to 'Back', locations_path %>
</div>

app/views/locations/show.html.erb
<div class = "show">
<br/>
<!--<p><%= gmaps4rails(@onelocation) %></p>-->

<%=gmaps({
       "map_options" => {"auto_zoom" => false, "zoom" => 12, "type" => 'TERRAIN', "center_latitude" => @location.latitude, "center_longitude" => @location.longitude },
       "onelocation"     => {"data" => @onelocation }
      })%>
<br/>
<h2><%= h(@location.tripday_date.strftime("%x"))%> - <%= @location.location_name%></h2>
<div class="rc"><%=RedCloth.new(@location.tripday_log).to_html.html_safe%></div>
<br/>
<p>
<%if admin?%>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
<%end%>
<%= link_to 'All points', blogs_path %>
</p>
</div>