config/routes.rb
Blogonhr::Application.routes.draw do

  resources :locations

  resources :blogs
  resources :dances   
  resources :homes
  resources :messages
  resources :movies
  resources :sessions
  
  match "/blogs", :to => "blogs#index"
  match "/dances", :to => "dances#index"
  match "/movies", :to => "movies#index"
  match "/contact" => "messages#new", :as => :contact
  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout
  
  

  
  root :to => "homes#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%= stylesheet_link_tag "alexstevenson", "scaffold"%>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<title>alexstevenson.com</title>
</head>
<body">
<div class="wrapper">
<div id="ars_branding"> 
    <div id="navbar">
    	<ul class="nav">
        	<li><%= link_to 'blog', blogs_path%></li>
            <li><%= link_to 'films', movies_path%></li>
            <li><%= link_to 'dance', dances_path%></li>
            <li><a href="#">design</a></li>
            <li><%= link_to 'contact', contact_path%></li>
        </ul>
	<!-- end navbar --></div>
<%=image_tag "alexstevenson_01.png", :width=>"1000",  :height=>"177", :alt=>"" %>	
<!-- end ars_branding --></div>
<div id="ars_content">
<%= yield %>
<!-- end ars_content --></div>
<div id="ars_footer"><%=image_tag "alexstevenson_footer.png", :width=>"1000", :height=>"177", :alt=>"" %>
<!-- end ars_footer --></div>
<!-- end wrapper --></div>
</body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>

<title>alexstevenson.com</title>
</head>
<div class="wrapper">
<body style="background-color:#FFFFFF;">
<div id="Table_01">
	<div id="alexstevenson-01_"> 
    <div id="navbar">
    	<ul class="nav">
        	<li><%= link_to 'blog', blogs_path%></li>
            <li><%= link_to 'films', movies_path%></li>
            <li><%= link_to 'dance', dances_path%></a></li>
            <li><a href="#">design</a></li>
            <li><%= link_to 'contact', contact_path%></li>
        </ul>
		</div>
		<%=image_tag "alexstevenson_01.png", :width=>"1000",  :height=>"177", :alt=>"" %>
  </div>
  <div id="alexstevenson-02_"><%= yield %></div>

      
	<!--<div id="alexstevenson-02_">
		<%=image_tag "alexstevenson_02.png", :width=>"1000",  :height=>"468", :alt=>"" %>
	</div>-->
<div class="push"></div>
</div>

<div id="alexstevenson-03_"><%=image_tag "alexstevenson_footer.png", :width=>"1000", :height=>"177", :alt=>"" %></div>
</body>
</div>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%= stylesheet_link_tag "alexstevenson", "blog", "scaffold"%>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<%=yield :head%>
<title>alexstevenson.com</title>
</head>
<body">
<div class="wrapper">
<div id="ars_branding"> 
    <div id="navbar">
    	<ul class="nav">
        	<li><%= link_to 'blog', blogs_path%></li>
            <li><%= link_to 'films', movies_path%></li>
            <li><%= link_to 'dance', dances_path%></li>
            <li><a href="#">design</a></li>
            <li><%= link_to 'contact', contact_path%></li>
        </ul>
	<!-- end navbar --></div>
<%=image_tag "alexstevenson_01.png", :width=>"1000",  :height=>"177", :alt=>"" %>	
<!-- end ars_branding --></div>
<%= yield%>
<div id="ars_footer"><%=image_tag "alexstevenson_footer.png", :width=>"1000", :height=>"177", :alt=>"" %>
<!-- end ars_footer --></div>
<!-- end wrapper --></div>
<%=yield :scripts%>
</body>
</html>

app/views/layouts/blognew.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%= stylesheet_link_tag "alexstevenson", "scaffold"%>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<%=yield :head%>
<title>alexstevenson.com</title>
</head>
<body">
<div class="wrapper">
<div id="ars_branding"> 
    <div id="navbar">
    	<ul class="nav">
        	<li><%= link_to 'blog', blogs_path%></li>
            <li><%= link_to 'films', movies_path%></li>
            <li><%= link_to 'dance', dances_path%></li>
            <li><a href="#">design</a></li>
            <li><%= link_to 'contact', contact_path%></li>
        </ul>
	<!-- end navbar --></div>
<%=image_tag "alexstevenson_01.png", :width=>"1000",  :height=>"177", :alt=>"" %>	
<!-- end ars_branding --></div>
<div id="ars_content">
<%= yield %>
<!-- end ars_content --></div>
<div id="ars_footer"><%=image_tag "alexstevenson_footer.png", :width=>"1000", :height=>"177", :alt=>"" %>
<!-- end ars_footerpoop --></div>
<!-- end wrapper --></div>
<%=yield :scripts%>
</body>
</html>

app/views/layouts/homes.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<title>alexstevenson.com</title>
</head>
<body>
<div class="wrapper">
	<div id="ars_branding"> 
    <div id="navbar">
    	<ul class="nav">
        	<li><%= link_to 'blog', blogs_path%></li>
            <li><%= link_to 'films', movies_path%></li>
            <li><%= link_to 'dance', dances_path%></a></li>
            <li><a href="#">design</a></li>
            <li><%= link_to 'contact', contact_path%></li>
        </ul>
	<!-- end navbar --></div>
		<%=image_tag "alexstevenson_01.png", :width=>"1000",  :height=>"177", :alt=>"" %>
  <!-- end ars_branding --></div>
      
	<div id="ars_content">
		<%=image_tag "alexstevenson_02.png", :width=>"1000", :alt=>"" %>
	<!-- end ars_content --></div>
<div id="ars_footer"><%=image_tag "alexstevenson_footer.png", :width=>"1000", :height=>"177", :alt=>"" %>
<!-- end ars_footer --></div>
<!-- end wrapper --></div>
</body>
</html>